/*
 * Copyright (C) 2011 Thedeath<www.fseek.org>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package jexplorer.ownComponents.fileTransferDialog;

import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import jexplorer.MainFrame;
import org.fseek.plugin.interfaces.MyFile;
import jexplorer.util.UtilBox;

/**
 *
 * @author Thedeath<www.fseek.org>
 */
public class FileIntegrateDialog extends javax.swing.JDialog
{   
    private int answer = -1;
    private MyFile fileFrom;
    private MyFile fileTo;
    
    private ImageIcon folderWarningIcon = new ImageIcon(MainFrame.selectedIconDirectory + File.separator + "folderWarning.png");
    private ImageIcon folderIcon = new ImageIcon(MainFrame.selectedIconDirectory + File.separator + "folderBig.png");
    /** Creates new form FileIntegrateDialog */
    private FileIntegrateDialog(java.awt.Frame parent, boolean modal, MyFile fileFrom, MyFile fileTo)
    {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.fileFrom = fileFrom;
        this.fileTo = fileTo;
        intDesign();
    }
    
    public static int showFileIntegrateDialog(java.awt.Frame parent, MyFile fileFrom, MyFile fileTo)
    {
        FileIntegrateDialog dia = new FileIntegrateDialog(parent, true, fileFrom, fileTo);
        dia.setVisible(true);
        return dia.getAnswer();
    }
    
    
    
    private void intDesign()
    {
        folderWarnLabel.setIcon(folderWarningIcon);
        firstSubPanelIcon.setIcon(folderIcon);
        secondSubPanelIcon.setIcon(folderIcon);
        subInfoLabel.setText("Das Ziel enthält bereits einen Ordner mit Namen \"" + fileTo.getFileName() + "\"");
        firstFileNameLabel.setText(fileFrom.getFileName());
        String format = UtilBox.fileDateToFormatString(fileFrom.getLastModified());
        firstCreateDateLabel.setText("Erstelldatum: " + format);
        secondFileNameLabel.setText(fileFrom.getFileName());
        format = UtilBox.fileDateToFormatString(fileTo.getLastModified());
        secondCreateDateLabel.setText("Erstelldatum: " + format);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        folderWarnLabel = new javax.swing.JLabel();
        mainInfoPanel = new javax.swing.JPanel();
        noButton = new javax.swing.JButton();
        yesButton = new javax.swing.JButton();
        secondSubPanel = new javax.swing.JPanel();
        secondSubPanelLabel = new javax.swing.JLabel();
        secondSubPanelIcon = new javax.swing.JLabel();
        secondSubPanelElementInfo = new javax.swing.JPanel();
        secondCreateDateLabel = new javax.swing.JLabel();
        secondFileNameLabel = new javax.swing.JLabel();
        firstSubPanel = new javax.swing.JPanel();
        firstSubPanelElementInfo = new javax.swing.JPanel();
        firstFileNameLabel = new javax.swing.JLabel();
        firstCreateDateLabel = new javax.swing.JLabel();
        firstSubPanelLabel = new javax.swing.JLabel();
        firstSubPanelIcon = new javax.swing.JLabel();
        subInfoLabel = new javax.swing.JLabel();
        mainInfoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ersetzen von Ordnern bestätigen");
        setResizable(false);

        folderWarnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/windows/folderWarning.png"))); // NOI18N

        noButton.setText("Nein");
        noButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noButtonActionPerformed(evt);
            }
        });

        yesButton.setText("Ja");
        yesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesButtonActionPerformed(evt);
            }
        });

        secondSubPanelLabel.setText("in diesen integrieren?");

        secondSubPanelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/windows/folderBig.png"))); // NOI18N

        secondCreateDateLabel.setText("Erstelldatum: 13.06.2011 19:41");

        secondFileNameLabel.setText("Neuer Ordner");

        javax.swing.GroupLayout secondSubPanelElementInfoLayout = new javax.swing.GroupLayout(secondSubPanelElementInfo);
        secondSubPanelElementInfo.setLayout(secondSubPanelElementInfoLayout);
        secondSubPanelElementInfoLayout.setHorizontalGroup(
            secondSubPanelElementInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondSubPanelElementInfoLayout.createSequentialGroup()
                .addGroup(secondSubPanelElementInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(secondFileNameLabel)
                    .addComponent(secondCreateDateLabel))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        secondSubPanelElementInfoLayout.setVerticalGroup(
            secondSubPanelElementInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondSubPanelElementInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(secondFileNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secondCreateDateLabel)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout secondSubPanelLayout = new javax.swing.GroupLayout(secondSubPanel);
        secondSubPanel.setLayout(secondSubPanelLayout);
        secondSubPanelLayout.setHorizontalGroup(
            secondSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(secondSubPanelIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secondSubPanelElementInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(secondSubPanelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );
        secondSubPanelLayout.setVerticalGroup(
            secondSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondSubPanelLayout.createSequentialGroup()
                .addComponent(secondSubPanelLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(secondSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(secondSubPanelIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(secondSubPanelElementInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        firstFileNameLabel.setText("Neuer Ordner");

        firstCreateDateLabel.setText("Erstelldatum: 13.06.2011 19:41");

        javax.swing.GroupLayout firstSubPanelElementInfoLayout = new javax.swing.GroupLayout(firstSubPanelElementInfo);
        firstSubPanelElementInfo.setLayout(firstSubPanelElementInfoLayout);
        firstSubPanelElementInfoLayout.setHorizontalGroup(
            firstSubPanelElementInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstSubPanelElementInfoLayout.createSequentialGroup()
                .addGroup(firstSubPanelElementInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstFileNameLabel)
                    .addComponent(firstCreateDateLabel))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        firstSubPanelElementInfoLayout.setVerticalGroup(
            firstSubPanelElementInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstSubPanelElementInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(firstFileNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstCreateDateLabel)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        firstSubPanelLabel.setText("Möchten Sie den Ordner");

        firstSubPanelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/windows/folderBig.png"))); // NOI18N

        javax.swing.GroupLayout firstSubPanelLayout = new javax.swing.GroupLayout(firstSubPanel);
        firstSubPanel.setLayout(firstSubPanelLayout);
        firstSubPanelLayout.setHorizontalGroup(
            firstSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstSubPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(firstSubPanelIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstSubPanelElementInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(firstSubPanelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );
        firstSubPanelLayout.setVerticalGroup(
            firstSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstSubPanelLayout.createSequentialGroup()
                .addComponent(firstSubPanelLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(firstSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstSubPanelElementInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstSubPanelIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        subInfoLabel.setFont(new java.awt.Font("Segoe UI", 0, 11));
        subInfoLabel.setText("Das Ziel enthält bereits einen Ordner mit Namen \"Neuer Ordner\".");

        mainInfoLabel.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        mainInfoLabel.setText("<html>Wenn Dateien denselben Namen haben, müssen Sie angeben, ob Sie die<br>Dateien ersetzen möchten.</html>");

        javax.swing.GroupLayout mainInfoPanelLayout = new javax.swing.GroupLayout(mainInfoPanel);
        mainInfoPanel.setLayout(mainInfoPanelLayout);
        mainInfoPanelLayout.setHorizontalGroup(
            mainInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainInfoPanelLayout.createSequentialGroup()
                .addContainerGap(245, Short.MAX_VALUE)
                .addComponent(yesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(subInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
            .addGroup(mainInfoPanelLayout.createSequentialGroup()
                .addComponent(mainInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(mainInfoPanelLayout.createSequentialGroup()
                .addGroup(mainInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(secondSubPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstSubPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        mainInfoPanelLayout.setVerticalGroup(
            mainInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainInfoPanelLayout.createSequentialGroup()
                .addComponent(subInfoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(firstSubPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(secondSubPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noButton)
                    .addComponent(yesButton)))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(folderWarnLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(folderWarnLabel)
                    .addComponent(mainInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yesButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_yesButtonActionPerformed
    {//GEN-HEADEREND:event_yesButtonActionPerformed
        answer = JOptionPane.YES_OPTION;
        this.dispose();
    }//GEN-LAST:event_yesButtonActionPerformed

    private void noButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_noButtonActionPerformed
    {//GEN-HEADEREND:event_noButtonActionPerformed
        answer = JOptionPane.NO_OPTION;
        this.dispose();
    }//GEN-LAST:event_noButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel firstCreateDateLabel;
    private javax.swing.JLabel firstFileNameLabel;
    private javax.swing.JPanel firstSubPanel;
    private javax.swing.JPanel firstSubPanelElementInfo;
    private javax.swing.JLabel firstSubPanelIcon;
    private javax.swing.JLabel firstSubPanelLabel;
    private javax.swing.JLabel folderWarnLabel;
    private javax.swing.JLabel mainInfoLabel;
    private javax.swing.JPanel mainInfoPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton noButton;
    private javax.swing.JLabel secondCreateDateLabel;
    private javax.swing.JLabel secondFileNameLabel;
    private javax.swing.JPanel secondSubPanel;
    private javax.swing.JPanel secondSubPanelElementInfo;
    private javax.swing.JLabel secondSubPanelIcon;
    private javax.swing.JLabel secondSubPanelLabel;
    private javax.swing.JLabel subInfoLabel;
    private javax.swing.JButton yesButton;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the answer
     */
    public int getAnswer()
    {
        return answer;
    }
}
