/*
 * Copyright (C) 2011 Thedeath<www.fseek.org>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package jexplorer.ownComponents.fileTable;

import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.table.JTableHeader;
import jexplorer.MainFrame;
import jexplorer.ownComponents.GrafikPanel;
import org.fseek.plugin.interfaces.MyFile;

/**
 *
 * @author Thedeath<www.fseek.org>
 */
public class FileTablePanel extends GrafikPanel
{

    private MainFrame frame;
    private MyFile file;

    /** Creates new form FileTablePanel */
    public FileTablePanel()
    {
        initComponents();
        //intDesign();
    }

    public FileTablePanel(MyFile file, MainFrame frame)
    {
        this.file = file;
        this.frame = frame;
        initComponents();
        intDesign();
    }
    
    public FileTablePanel(MainFrame frame)
    {
        this.frame = frame;
        this.file = null;
        initComponents();
        intDesign();
    }

    private void intDesign()
    {
        this.setBorder(BorderFactory.createEmptyBorder());
        JTableHeader tableHeader = getFileTable().getTableHeader();
        tableHeader.setOpaque(true);
        tableHeader.setOpaque(false);
        tableHeader.setBackground(MainFrame.colorizer.getMainBackgroundColor());
        tableHeader.setDefaultRenderer(new MyHeaderCellRenderer(tableHeader.getDefaultRenderer()));
        tablePanel.add(tableHeader, BorderLayout.NORTH);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablePanel = new javax.swing.JPanel();
        fileTable = new jexplorer.ownComponents.fileTable.FileTable();

        setBackground(new java.awt.Color(255, 255, 255));

        tablePanel.setOpaque(false);
        tablePanel.setLayout(new java.awt.BorderLayout());

        fileTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        fileTable = null;
        if(file == null)
        {
            fileTable = FileTable.create(frame);
        }
        else
        {
            fileTable = FileTable.create(file, frame);
        }
        tablePanel.add(fileTable, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jexplorer.ownComponents.fileTable.FileTable fileTable;
    private javax.swing.JPanel tablePanel;
    // End of variables declaration//GEN-END:variables


    /**
     * @return the frame
     */
    public MainFrame getFrame()
    {
        return frame;
    }

    /**
     * @param frame the frame to set
     */
    public void setFrame(MainFrame frame)
    {
        this.frame = frame;
    }

    /**
     * @return the file
     */
    public MyFile getFile()
    {
        return file;
    }

    /**
     * @param file the file to set
     */
    public void setFile(MyFile file)
    {
        this.file = file;
    }

    /**
     * @return the fileTable
     */
    public FileTable getFileTable()
    {
        return fileTable;
    }
}
