/*
 * www.fseek.org
 * ~Thedeath
 * 2010 - 2011
 */

/*
 * HardwareComp.java
 *
 * Created on 16.04.2011, 16:56:04
 */
package org.fseek.components;

import java.awt.event.KeyEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Thedeath<www.fseek.org>
 */
public abstract class ViewComponent extends javax.swing.JPanel
{

    protected Icon icon;
    protected Icon smallIcon;
    protected SelectHandler sh;
    protected CompEffects compEffects;

    /** Creates new form HardwareComp */
    public ViewComponent(SelectHandler sh, CompEffects compEffects)
    {
        this.sh = sh;
        this.compEffects = compEffects;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        progressBarPanel = new javax.swing.JPanel();
        spaceLabel = new javax.swing.JLabel();

        setOpaque(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jPanel1.setOpaque(false);

        nameLabel.setFont(new java.awt.Font("Segoe UI", 0, 12));
        nameLabel.setText("Name");

        progressBarPanel.setOpaque(false);
        progressBarPanel.setLayout(new java.awt.GridLayout(1, 0));

        spaceLabel.setFont(new java.awt.Font("Segoe UI", 0, 12));
        spaceLabel.setText("undefined");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(progressBarPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(spaceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(spaceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(iconLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_formMouseEntered
    {//GEN-HEADEREND:event_formMouseEntered
        mouseOverEffect(true);
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_formMouseExited
    {//GEN-HEADEREND:event_formMouseExited
        mouseOverEffect(false);
    }//GEN-LAST:event_formMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_formMouseClicked
    {//GEN-HEADEREND:event_formMouseClicked
        this.requestFocus();
        if (evt.getClickCount() == 2)
        {
            ImageIcon ic = (ImageIcon) this.getSmallIcon();
            if (ic == null)
            {
                ic = (ImageIcon) this.getIcon();
            }
            mouseClick(ic);
        }
    }//GEN-LAST:event_formMouseClicked

    public abstract void mouseClick(ImageIcon icon);

    private void formKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_formKeyReleased
    {//GEN-HEADEREND:event_formKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            ImageIcon ic = (ImageIcon) this.getSmallIcon();
            if (ic == null)
            {
                ic = (ImageIcon) this.getIcon();
            }
            mouseClick(ic);
        }
    }//GEN-LAST:event_formKeyReleased

    private void formFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_formFocusGained
    {//GEN-HEADEREND:event_formFocusGained
        sh.clearSelection();
        sh.addSelection(this);
    }//GEN-LAST:event_formFocusGained

    private void formFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_formFocusLost
    {//GEN-HEADEREND:event_formFocusLost
        sh.removeSelection(this);
    }//GEN-LAST:event_formFocusLost

    public void mouseOverEffect(boolean bol)
    {
        if (!sh.contains(this))
        {
            compEffects.mouseOver(bol, this);
        }
    }

    public void informInvisible()
    {
        mouseOverEffect(false);
    }

    public void setIcon(Icon icon)
    {
        this.icon = icon;
        iconLabel.setIcon(icon);
    }

    public Icon getIcon()
    {
        return this.icon;
    }

    public void setCompName(String name)
    {
        this.nameLabel.setText(name);
    }

    public String getCompName()
    {
        return this.nameLabel.getText();
    }

    /**
     * @return the smallIcon
     */
    public Icon getSmallIcon()
    {
        return smallIcon;
    }

    /**
     * @param smallIcon the smallIcon to set
     */
    public void setSmallIcon(Icon smallIcon)
    {
        this.smallIcon = smallIcon;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel iconLabel;
    protected javax.swing.JPanel jPanel1;
    protected javax.swing.JLabel nameLabel;
    protected javax.swing.JPanel progressBarPanel;
    protected javax.swing.JLabel spaceLabel;
    // End of variables declaration//GEN-END:variables
}
